version: '3'
services:
  db:
    image: postgres:10.7
    ports:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env
      - ./apac-api-proxy/.env
    environment:
      RAILS_ENV: production
      RACK_ENV: production
    command: bash -c "rm -fR tmp/pids/* ; puma -p 3000 -C config/puma.rb"
    volumes:
      - ./apac-api-proxy:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apac-api-proxy/public:/app/public
    links:
      - web
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
    links:
      - web